---
- name: Deploy Ansible Lab
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.lab.git"
    vcenter_username: "s00@lab.git"
    vcenter_password: "VMware123!"
    datacenter_name: "Datacenter" 
    esxi_username: "root"
    esxi_password: "VMware123!"
    parent_folder: "2.Students/" 
    datastore_name: "vsanDatastore" 
    template_jumpbox: "250827-DC"
    snapshot_name: "Template"
    vm_portgroup:
    - "{{ student_id }}-Mgmt"

    LAB_SID: 
    - { id: S00, host: 10.50.141.11 }
    - { id: S01, host: 10.50.141.12 }
    - { id: S02, host: 10.50.141.13 }
    - { id: S03, host: 10.50.141.14 }
    - { id: S04, host: 10.50.141.11 }
    - { id: S05, host: 10.50.141.12 }
    - { id: S06, host: 10.50.141.13 }
    - { id: S07, host: 10.50.141.14 }
    - { id: S08, host: 10.50.141.11 }
    - { id: S09, host: 10.50.141.12 }
    - { id: S10, host: 10.50.141.13 }
    - { id: S11, host: 10.50.141.14 }
    - { id: S12, host: 10.50.141.11 }
    - { id: S13, host: 10.50.141.12 }
    - { id: S14, host: 10.50.141.13 }
    - { id: S15, host: 10.50.141.14 }
    - { id: S16, host: 10.50.141.12 }
    - { id: S17, host: 10.50.141.13 }

  tasks:
  - name: 01. Create LAB VM Folder
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder_type: vm
      folder_name: "{{ item.id }}"
      parent_folder: "{{ parent_folder }}"
      state: present
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: sub_folder_creation_result

  - name: 02. Create LAB Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: "{{ item.host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: false
      switch: "{{ item.id }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True      
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: lab_switch_creation_result

  - name: 03. Adding Trunk Portgroup to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ item.host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ item.host }}"
      validate_certs: no
      switch: "{{ item.id }}"
      portgroup: "{{ item.id }}-Trunk"
      vlan_id: 4095
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: lab_trunk_port_creation_result
    when: lab_switch_creation_result.msg == "All items completed"

  - name: 04. Adding Mgmt Portgroup to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ item.host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ item.host }}"
      validate_certs: no
      switch: "{{ item.id }}"
      portgroup: "{{ item.id }}-Mgmt"
      vlan_id: 10
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: lab_mgmt_port_creation_result
    when: lab_trunk_port_creation_result.msg == "All items completed"

  - name: 05. Deploy Lab DC vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-DC"
      state: "poweredon"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ item.parent }}{{ item.id }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ datastore_name }}"
      template: "{{ template_jumpbox }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
      networks:
        - name: "{{ item.id }}-Trunk"
          label: "Network adapter 1"
        - name: "VM-10.50.141"
          label: "Network adapter 2"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: lab_vm_creation_result
    when: lab_mgmt_port_creation_result.msg == "All items completed"

  - name: 06. waiting DC VM Booting
    wait_for:
      timeout: 120
    delegate_to: localhost

  - name: 07. Install HopToDesk Program in DC VM
    community.vmware.vmware_vm_shell:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      vm_id: "{{ item.id }}-DC"
      vm_id_type: vm_name
      vm_username: Administrator
      vm_password: VMware1!
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: '-command "(c:\Material\HopToDesk.exe)"'
      vm_shell_cwd: 'c:\Users\Administrator'
      wait_for_process: True
      timeout: 240
    loop: "{{ LAB_SID }}"
    delegate_to: localhost
    register: Install_Program_result

