---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "DPG-172.0.10.x"
    datastore_name: "vsanDatastore"
    dc_template_name: "LIG-ad.vclass.local"
    snapshot_name: "linked"

    SID_ESXi: 
    - { id: S11, host: 172.0.10.12 }
    - { id: S12, host: 172.0.10.13 }

    VMs_Setup:
    - { vm_name: -SA-ESXi-02, host_name: sa-esxi-02, ip_addr: 10.10.10.12 }
    - { vm_name: -SA-ESXi-03, host_name: sa-esxi-03, ip_addr: 10.10.10.13 }
    - { vm_name: -SA-ESXi-04, host_name: sa-esxi-04, ip_addr: 10.10.10.14 }

    PG_vLAN:
    - { name: -SA-Mgmt, vlan: 10 }
    - { name: -SA-Storage, vlan: 11 }
    - { name: -SA-vMotion, vlan: 12 }
    - { name: -SA-Prod, vlan: 13 }
    - { name: -Trunk, vlan: 4095 }

    ESXi_NICs:
    - { label: "Network adapter 1", pg: -SA-Mgmt }
    - { label: "Network adapter 2", pg: -SA-Mgmt }
    - { label: "Network adapter 3", pg: -Trunk }
    - { label: "Network adapter 4", pg: -Trunk }


  tasks: 
  - name: 01. Create a Project folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ item.id }}'
      parent_folder: '{{ parent_folder }}'
      state: present
    loop: "{{ SID_ESXi }}"  
    register: sub_folder_creation_result
    delegate_to: localhost


  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ item.host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ item.id }}'
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 03. waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost


  - name: 04. Adding Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id }}"
      portgroup: "{{ item[0].id + item[1].name }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: '{{ item[1].vlan | int }}'
    loop: "{{ SID_ESXi | product(PG_vLAN) | list }}"      
    delegate_to: localhost


  - name: 04. Deploy Router(VyOS) OVA
    community.vmware.vmware_deploy_ovf:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: '{{ datastore_name }}'
      name: "{{ item.id + '-Router' }}"
      networks: { 'Lab-Outside': "{{ public_net }}", 'Lab-Inside': "{{ item.id + '-Trunk' }}" }
      ovf: /mnt/c/Material/temp-vyos-1.4.ova    
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 05. waiting Router Booting
    wait_for:
      timeout: 60
    delegate_to: localhost    


  - name: 06. Configure Router(VyOS)
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      vm_id: "{{ item.id + '-Router' }}"
      vm_id_type: vm_name
      vm_username: 'vyos'
      vm_password: 'vyos'
      vm_shell: /bin/vbash
      vm_shell_cwd: "/tmp"
      vm_shell_args: |-
        -c "source /opt/vyatta/etc/functions/script-template
        configure
          set system login user admin full-name Admin_User
          set system login user admin authentication plaintext-password VMware1!
          set service ssh port 22
            
          set system ipv6 disable
          
          set interfaces ethernet eth0 address dhcp
          set interfaces ethernet eth0 description Outside
          set interfaces ethernet eth0 ipv6 address no-default-link-local
          set protocols static route 0.0.0.0/0 next-hop 172.0.10.1

          set interfaces ethernet eth1 vif 10 description 'VLAN 10 - Site A Management'
          set interfaces ethernet eth1 vif 10 address 10.10.10.1/24
          set interfaces ethernet eth1 vif 10 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 11 description 'VLAN 11 - Site A Storage'
          set interfaces ethernet eth1 vif 11 address 10.10.11.1/24
          set interfaces ethernet eth1 vif 11 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 12 description 'VLAN 12 - Site A vMotion'
          set interfaces ethernet eth1 vif 12 address 10.10.12.1/24
          set interfaces ethernet eth1 vif 12 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 13 description 'VLAN 13 - Site A Production'
          set interfaces ethernet eth1 vif 13 address 10.10.13.1/24
          set interfaces ethernet eth1 vif 13 ipv6 address no-default-link-local

          set system name-server 172.0.10.2
          set service ntp server kr.pool.ntp.org
                      
          set nat source rule 10 outbound-interface eth0
          set nat source rule 10 source address 10.10.10.0/24
          set nat source rule 10 translation address masquerade

          set nat source rule 13 outbound-interface eth0
          set nat source rule 13 source address 10.10.13.0/24
          set nat source rule 13 translation address masquerade
          
        commit
        save"
      wait_for_process: True
      timeout: 180
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost
    register: shell_command_with_wait_timeout        


  - name: 07. Linked Clone for Domain Controller
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-DC' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ dc_template_name }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
    loop: "{{ SID_ESXi }}"  
    delegate_to: localhost


  - name: 08. Perform vMotion of virtual machine
    community.vmware.vmware_vmotion:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      vm_name: "{{ item.id + '-DC' }}"
      destination_host: "{{ item.host }}"
    loop: "{{ SID_ESXi }}"    
    delegate_to: localhost


  - name: 09. Change network - DC VM
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no      
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      name: "{{ item.id + '-DC' }}"
      label: "Network adapter 1"
      network_name: "{{ item.id + '-SA-Mgmt' }}"
    loop: "{{ SID_ESXi }}"    
    delegate_to: localhost


  - name: 10. Poweron DC VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-DC' }}"
      state: "poweredon"
      state_change_timeout: 60
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 11. Deploy -SA-ESXi-01 (None Installed ESXi vm)
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-SA-ESXi-01'}}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "LIG-ESXi-Install"
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 12. Change SA-ESXi-01 VM Nics
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + '-SA-ESXi-01'}}"
      label: "{{ item[1].label }}"
      network_name: "{{ item[0].id + item[1].pg }}"
      state: present
      force: yes
    loop: "{{ SID_ESXi | product(ESXi_NICs) | list }}"
    delegate_to: localhost


  - name: 13. Clone multiple esxi vms from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + item[1].vm_name }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item[0].id }}"
      esxi_hostname: '{{ item[0].host }}'
      datastore: "{{ datastore_name }}"
      template: "LIG-ESXi-Installed"
    loop: "{{ SID_ESXi | product(VMs_Setup) | list }}"
    delegate_to: localhost


  - name: 14. Change SA-ESXi-02 VM Nics
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + '-SA-ESXi-02'}}"
      label: "{{ item[1].label }}"
      network_name: "{{ item[0].id + item[1].pg }}"
      state: present
      force: yes
    loop: "{{ SID_ESXi | product(ESXi_NICs) | list }}"
    delegate_to: localhost


  - name: 15. Change SA-ESXi-03 VM Nics
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + '-SA-ESXi-03'}}"
      label: "{{ item[1].label }}"
      network_name: "{{ item[0].id + item[1].pg }}"
      state: present
      force: yes
    loop: "{{ SID_ESXi | product(ESXi_NICs) | list }}"
    delegate_to: localhost


  - name: 16. Change SA-ESXi-04 VM Nics
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + '-SA-ESXi-03'}}"
      label: "{{ item[1].label }}"
      network_name: "{{ item[0].id + item[1].pg }}"
      state: present
      force: yes
    loop: "{{ SID_ESXi | product(ESXi_NICs) | list }}"
    delegate_to: localhost


  - name: 17. Power on ESXi VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id + item[1].vm_name }}"
      state: "poweredon"
    loop: "{{ SID_ESXi | product(VMs_Setup) | list }}"
    delegate_to: localhost


  - name: 18. Waiting boot-up
    wait_for:
      timeout: 120
    delegate_to: localhost


  - name: 19. Configure Site-A ESXi VMs
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item[0].id }}"
      vm_id: "{{ item[0].id + item[1].vm_name }}"
      vm_id_type: vm_name
      vm_username: 'root'
      vm_password: 'VMware1!'
      vm_shell: /bin/sh
      vm_shell_cwd: "/tmp"
      vm_shell_args: |
        echo "Don't remove this line. Write your ESXi configuration commands below."
        esxcli system settings advanced set -o /Net/FollowHardwareMac -i 1
        sed -i 's#/system/uuid.*##' /etc/vmware/esx.conf
        esxcli network vswitch standard uplink add -u vmnic1 -v vSwitch0
        esxcli network ip interface ipv4 set -i vmk0 -t static -I {{ item[1].ip_addr }} -N 255.255.255.0 -g 10.10.10.1
        esxcli network ip route ipv4 add -n 0.0.0.0 -g 10.10.10.1
        esxcli network ip dns server add -s 10.10.10.2
        esxcli system hostname set --host {{ item[1].host_name }}
        esxcli system hostname set --domain vclass.local
        esxcli system ntp set -e yes -s 10.10.10.1
        vim-cmd hostsvc/enable_ssh
        vim-cmd hostsvc/enable_esx_shell
        vim-cmd hostsvc/advopt/update UserVars.SuppressShellWarning long 1
        /sbin/generate-certificates
        /sbin/auto-backup.sh
      wait_for_process: True
    loop: "{{ SID_ESXi | product(VMs_Setup) | list }}"


  - name: 20. Reboot SA-ESXi VMs
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: 'false'        
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item[0].id }}"
      name: "{{ item[0].id + item[1].vm_name }}"
      state: reboot-guest
    loop: "{{ SID_ESXi | product(VMs_Setup) | list }}"
    delegate_to: localhost


  - name: 21. Deploy vCenter Server Appliance VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-VCSA' }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ datacenter_name + '/vm/' + parent_folder + '/' + item.id }}"
      esxi_hostname: '{{ item.host }}'
      datastore: "{{ datastore_name }}"
      template: "LIG-VCSA-Installed"
      linked_clone: True
      snapshot_src: "Installed"
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 22. Change VCSA VM Network Interfaces
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-VCSA' }}"
      label: "Network adapter 1"
      network_name: "{{ item.id + '-SA-Mgmt' }}"
      state: present
      force: yes
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost


  - name: 23. Poweron VCSA VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id + '-VCSA' }}"
      state: "poweredon"
      state_change_timeout: 60
    loop: "{{ SID_ESXi }}"
    delegate_to: localhost

