---
- name: Deploy Ansible Lab
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3

    student_id: "A00"                                ## 해당값을 변경해 주세요. 폴더/스위치/포트그룹/VM명을 유니크하게 사용하기 위해서 사용됩니다.

    vcenter_hostname: "sb-vcsa-01.lab.git"           ## student_id 값에 따라서 접속해야할 vCenter가 다른경우에는 변경해주시길 바랍니다.
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"

    datacenter_name: "SB-Datacenter"                 ## student_id 값에 따라서 접속해야할 vCenter/Datacenter가 다른경우에는 변경해주시길 바랍니다.
    cluster_name: "SB-vSAN"                          ## student_id 값에 따라서 접속해야할 vCenter/Cluster가 다른경우에는 변경해주시길 바랍니다.
    esxi_hostname: "sb-esxi-01.lab.git"              ## student_id 값에 따라서 접속해야할 vCenter/ESXi서버가 다른경우에는 변경해주시길 바랍니다.
    esxi_username: "root"
    esxi_password: "VMware1!"

    parent_folder: "3.SB-Students/"                  ## student_id 값에 따라서 접속해야할 vCenter/VM Folder가 다른경우에는 변경해주시길 바랍니다.

    datastore_name: "sb-vSAN"                        ## student_id 값에 따라서 접속해야할 vCenter/Datastore가 다른경우에는 변경해주시길 바랍니다.
    
    uplink_portgroup: "VM-10.50.142.x"               ## 라우팅/NAT를 진행할 포트 그룹을 지정하세요. "VM-10.50.141.x" "VM-10.50.142.x" "VM-10.50.143.x"
    downlink_portgroup: '{{student_id}}-Ansible'     ## 생성된 LAB 스위치/포트그룹중 내부 연결을 위한 포트그룹을 선택해 주세요. 예: S00-SA-Mgmt, A00-Ansible

    template_jumpbox: "Temp-AD-NAT-WSL"
    snapshot_name: "Installed"


  tasks:
    - name: 01. Make a Lab VM list
      community.vmware.vmware_vm_info:
        hostname: '{{ vcenter_hostname }}'
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: '{{ datacenter_name }}/vm/{{ parent_folder }}{{ student_id }}'
      register: lab_vms

    - name: 02. Stop Lab VMs in the folder
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.guest_name }}"
        state: powered-off
      loop: "{{ lab_vms.virtual_machines }}"

    - name: 03. Delete Lab VMs in the folder
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: '{{ datacenter_name }}/vm/{{ parent_folder }}{{ student_id }}'
        name: "{{ item.guest_name }}"
        state: absent
      loop: "{{ lab_vms.virtual_machines }}"

    - name: 04. Remove LAB Standard vSwitch
      community.vmware.vmware_vswitch:
        hostname: '{{ esxi_hostname }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: false
        switch: '{{ student_id }}'
        state: absent
      delegate_to: localhost

    - name: 05. Remove LAB VM Folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder_type: vm
        folder_name: '{{ student_id }}'
        parent_folder: '{{ parent_folder }}'
        state: absent
      delegate_to: localhost
