---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    student_id: "S00"
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"
    esxi_hostname: "172.0.10.13"
    template_name: "temp-iac"
    snapshot_name: "linked"
    datastore_name: "vsanDatastore"    
    
  tasks:
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-linked_clone  
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-customization
  - name: 06. Linked Clone Windows Server for Domain Controller
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_id + '-DC' }}"
      state: "poweredon"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ folder_name }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "{{ template_name }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
      networks:
      - name: "{{ student_id + '-SA-Mgmt' }}"
        connected: True
        start_connected: True
        ip: 10.10.10.2
        netmask: 255.255.255.0
        gateway: 10.10.10.1
        dns_servers: 172.0.10.2
        type: static
      customization:
        password: VMware1!
      wait_for_customization: yes
      wait_for_customization_timeout: 300
    delegate_to: localhost
