---
- hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "sa-vcsa-01.lab.git"
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"
    datacenter_name: "SA-Datacenter"
    students:
      - S00
      - S01
      - S02
      - S03
      - S04
      - S05
      - S06

  tasks: 
    - name: Create a Students folder
      community.vmware.vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ datacenter_name }}'
        folder_name: '{{ item }}'
        parent_folder: "3.SA-Students"
        state: present
      register: sub_folder_creation_result
      loop: '{{ students }}'
      delegate_to: localhost
