---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    cluster_name: "vSAN"
    datastore_name: "vsanDatastore"
    template_name: "Win-IaC"
    snapshot_src_name: "2022-09"
    folder_prefix: "1.Internal-Training/Students/"
    full_folder_prefix: "Datacenter/vm/1.Internal-Training/Students/"

  tasks:
  - name: Create a sub folder under VM folder on given datacenter
    community.vmware.vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ datacenter_name }}'
        folder_type: vm
        folder_name: '{{ item }}'
        parent_folder: '{{ folder_prefix }}'
        state: present
    loop:
      - S00
      - S01
      - S02
      - S03
      - S04
      - S05
      - S06
      - S07
      - S08
      - S09
      - S10
      - S11
      - S12
      - S13
      - S14
      - S15
      - S16
      - S17      
    register: sub_folder_creation_result
    delegate_to: localhost

  - name: Deploy IaC(Infrastructure as a Code) VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.vm_name + '-IaC' }}"
      state: "poweredon"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + item.vm_name }}"
      esxi_hostname: '{{ item.esxi_host }}'
      datastore: "{{ datastore_name }}"
      template: "{{ template_name }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_src_name }}"
    loop:
      - { vm_name: S00, esxi_host: 172.0.10.13 }
      - { vm_name: S01, esxi_host: 172.0.10.11 }
      - { vm_name: S02, esxi_host: 172.0.10.12 }
      - { vm_name: S03, esxi_host: 172.0.10.13 }
      - { vm_name: S04, esxi_host: 172.0.10.11 }
      - { vm_name: S05, esxi_host: 172.0.10.12 }
      - { vm_name: S06, esxi_host: 172.0.10.13 }
      - { vm_name: S07, esxi_host: 172.0.10.11 }
      - { vm_name: S08, esxi_host: 172.0.10.12 }
      - { vm_name: S09, esxi_host: 172.0.10.13 }
      - { vm_name: S10, esxi_host: 172.0.10.11 }
      - { vm_name: S11, esxi_host: 172.0.10.12 }
      - { vm_name: S12, esxi_host: 172.0.10.13 }
      - { vm_name: S13, esxi_host: 172.0.10.11 }      
      - { vm_name: S14, esxi_host: 172.0.10.12 }
      - { vm_name: S15, esxi_host: 172.0.10.13 }
      - { vm_name: S16, esxi_host: 172.0.10.11 }
      - { vm_name: S17, esxi_host: 172.0.10.12 }      
    delegate_to: localhost
    
