---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    cluster_name: "vSAN"
    folder_prefix: "1.Internal-Training/Students/"
    full_folder_prefix: "Datacenter/vm/1.Internal-Training/Students/"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no

    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:172.0.10.13)?
      private: no

  tasks: 

    - name: Deploy VyOS ova
      community.vmware.vmware_deploy_ovf:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + student_ID }}"
          esxi_hostname: '{{ esxi_hostname }}'
          datastore: 'vsanDatastore'
          name: "{{ student_ID + '-Router' }}"
          networks: { 'DPG-172.0.10.x': "DPG-172.0.10.x", 'DPG-172.0.20.x': "{{ student_ID + '-Trunk' }}" }
          power_on: yes
          ovf: /mnt/c/Material/temp-vyos-1.4.ova    
      delegate_to: localhost


    - name: Waiting 60 seconds for completing bootup
      wait_for:
        timeout: 60
      delegate_to: localhost


    - name: VyOS Router Configuration
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + student_ID }}"
          vm_id: "{{ student_ID + '-Router' }}"
          vm_id_type: vm_name
          vm_username: 'vyos'
          vm_password: 'vyos'
          vm_shell: /bin/vbash
          vm_shell_cwd: "/tmp"
          vm_shell_args: |-
            -c "source /opt/vyatta/etc/functions/script-template
            configure
            set system login user admin full-name Admin_User
            set system login user admin authentication plaintext-password VMware1!
            set service ssh port 22
            
            set interfaces ethernet eth0 address dhcp
            set interfaces ethernet eth0 description Outside
            set protocols static route 0.0.0.0/0 next-hop 172.0.10.1
            
            set system name-server 172.0.10.2
            set system ntp server kr.pool.ntp.org

            set interfaces ethernet eth1 vif 10 description 'VLAN 10 - Site A Management'
            set interfaces ethernet eth1 vif 10 address 10.10.10.1/24
            set interfaces ethernet eth1 vif 11 description 'VLAN 11 - Site A Storage'
            set interfaces ethernet eth1 vif 11 address 10.10.11.1/24
            set interfaces ethernet eth1 vif 12 description 'VLAN 12 - Site A vMotion'
            set interfaces ethernet eth1 vif 12 address 10.10.12.1/24
            set interfaces ethernet eth1 vif 13 description 'VLAN 13 - Site A Production'
            set interfaces ethernet eth1 vif 13 address 10.10.13.1/24

            set interfaces ethernet eth1 vif 20 description 'VLAN 20 - Site B Management'
            set interfaces ethernet eth1 vif 20 address 10.10.20.1/24
            set interfaces ethernet eth1 vif 21 description 'VLAN 21 - Site B Storage'
            set interfaces ethernet eth1 vif 21 address 10.10.21.1/24
            set interfaces ethernet eth1 vif 22 description 'VLAN 22 - Site B vMotion'
            set interfaces ethernet eth1 vif 22 address 10.10.22.1/24
            set interfaces ethernet eth1 vif 23 description 'VLAN 23 - Site B Production'
            set interfaces ethernet eth1 vif 23 address 10.10.23.1/24

            set interfaces ethernet eth1 vif 30 description 'VLAN 30 - SiteC Management'
            set interfaces ethernet eth1 vif 30 address 10.10.30.1/24

            set interfaces ethernet eth1 vif 100 description 'VLAN 100 - vSAN'
            set interfaces ethernet eth1 vif 100 address 10.10.100.1/24
            
            set nat source rule 100 outbound-interface eth0
            set nat source rule 100 source address 10.10.10.0/24
            set nat source rule 100 translation address masquerade
            
            commit
            save"
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout
