---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    sa_vcsa : "sa-vcsa-01.lab.git"
    sb_vcsa : "sb-vcsa-01.lab.git"
    sc_vcsa : "sc-vcsa-01.lab.git"
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"
    sa_dc: "SA-Datacenter"
    sa_cluster: "SA-vSAN"
    sa_ds: "SA-vSAN"
    sa_fn: "3.SA-Students/"
    sb_dc: "SB-Datacenter"
    sb_cluster: "SB-vSAN"
    sb_ds: "SB-vSAN"
    sb_fn: "3.SB-Students/"
    sc_dc: "SC-Datacenter"
    sc_cluster: "SC-vSAN"
    sc_ds: "SC-vSAN"
    sc_fn: "3.SC-Students/"
    id: "S00"


  tasks:
  - name: Create a sub folder under VM folder on given datacenter
    community.vmware.vcenter_folder:
      hostname: '{{ item.VCSA }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{ item.DC }}'
      folder_type: vm
      folder_name: '{{ item.ID }}'
      parent_folder: '{{ item.FN }}'
      state: present
    loop:
      - { VCSA: '{{ sa_vcsa }}' , DC: '{{ sa_dc }}', FN: '{{ sa_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sb_vcsa }}' , DC: '{{ sb_dc }}', FN: '{{ sb_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sc_vcsa }}' , DC: '{{ sc_dc }}', FN: '{{ sc_fn }}', ID: '{{ id }}'  }
    register: sub_folder_creation_result
    delegate_to: localhost
