---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    sa_vcsa : "sa-vcsa-01.lab.git"
    sb_vcsa : "sb-vcsa-01.lab.git"
    sc_vcsa : "sc-vcsa-01.lab.git"
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"
    sa_dc: "SA-Datacenter"
    sa_cluster: "SA-vSAN"
    sa_ds: "sa-vSAN"
    sa_fn: "3.SA-Students/"
    sb_dc: "SB-Datacenter"
    sb_cluster: "SB-vSAN"
    sb_ds: "sa-vSAN"
    sb_fn: "3.SB-Students/"
    sc_dc: "SC-Datacenter"
    sc_cluster: "SC-vSAN"
    sc_ds: "sc-vSAN"
    sc_fn: "3.SC-Students/"
    id: "S00"
    sa_esxi: "sa-esxi-01.lab.git"
    sb_esxi: "sb-esxi-01.lab.git"
    sc_esxi: "sc-esxi-01.lab.git"
    esxi_username: "root"
    esxi_password: "VMware1!"
    sa_temp_router: "Temp-Router"
    sa_router_uppg: "VM-10.50.141.x"


  tasks:
  - name: 01. Create LAB VM Folder
    community.vmware.vcenter_folder:
      hostname: '{{ item.VCSA }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{ item.DC }}'
      folder_type: vm
      folder_name: '{{ item.ID }}'
      parent_folder: '{{ item.FN }}'
      state: present
    loop:
      - { VCSA: '{{ sa_vcsa }}' , DC: '{{ sa_dc }}', FN: '{{ sa_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sb_vcsa }}' , DC: '{{ sb_dc }}', FN: '{{ sb_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sc_vcsa }}' , DC: '{{ sc_dc }}', FN: '{{ sc_fn }}', ID: '{{ id }}'  }
    register: sub_folder_creation_result
    delegate_to: localhost


  - name: 02. Create LAB Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ item.host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ item.vswitch }}'
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    loop:
      - { host: '{{ sa_esxi }}' , vswitch: '{{ id }}-SA'  }
      - { host: '{{ sb_esxi }}' , vswitch: '{{ id }}-SB'  }
      - { host: '{{ sc_esxi }}' , vswitch: '{{ id }}-SC'  }
    delegate_to: localhost

  - name: 03. waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost

  - name: 04. Adding Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: '{{ item.host }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      esxi_hostname: "{{ item.host }}"
      validate_certs: no
      switch: "{{ item.vswitch }}"
      portgroup: "{{ item.pg }}"
      vlan_id: '{{ item.vlan }}'
    loop:
      - { host: '{{ sa_esxi }}', vswitch: '{{ id }}-SA', pg: '{{ id }}-SA-Trunk', vlan: 4095 }
      - { host: '{{ sa_esxi }}', vswitch: '{{ id }}-SA', pg: '{{ id }}-SA-Mgmt', vlan: 10 }
      - { host: '{{ sa_esxi }}', vswitch: '{{ id }}-SA', pg: '{{ id }}-SA-vSAN', vlan: 11 }
      - { host: '{{ sa_esxi }}', vswitch: '{{ id }}-SA', pg: '{{ id }}-SA-vMotion', vlan: 12 }
      - { host: '{{ sa_esxi }}', vswitch: '{{ id }}-SA', pg: '{{ id }}-SA-Prod', vlan: 13 }
      - { host: '{{ sb_esxi }}', vswitch: '{{ id }}-SB', pg: '{{ id }}-SB-Trunk', vlan: 4095 }
      - { host: '{{ sb_esxi }}', vswitch: '{{ id }}-SB', pg: '{{ id }}-SB-Mgmt', vlan: 20 }
      - { host: '{{ sb_esxi }}', vswitch: '{{ id }}-SB', pg: '{{ id }}-SB-vSAN', vlan: 21 }
      - { host: '{{ sb_esxi }}', vswitch: '{{ id }}-SB', pg: '{{ id }}-SB-vMotion', vlan: 22 }
      - { host: '{{ sb_esxi }}', vswitch: '{{ id }}-SB', pg: '{{ id }}-SB-Prod', vlan: 23 }
      - { host: '{{ sc_esxi }}', vswitch: '{{ id }}-SC', pg: '{{ id }}-SC-Mgmt', vlan: 30 }
      - { host: '{{ sc_esxi }}', vswitch: '{{ id }}-SC', pg: '{{ id }}-SC-vSAN', vlan: 31 }
    delegate_to: localhost


  - name: 05. Deploy SiteA Router
    community.vmware.vmware_guest:
      hostname: "{{ sa_vcsa }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.router }}"
      state: "poweredoff"
      datacenter: '{{ sa_dc }}'
      folder: '{{ sa_fn }}{{ id }}'
      esxi_hostname: '{{ sa_esxi }}'
      datastore: '{{ sa_ds }}'
      template: '{{ sa_temp_router }}'
      networks:
        - name: "{{ sa_router_uppg }}"
          label: "Network adapter 1"
          connected: True
          start_connected: True
        - name: "{{ item.downpg }}"
          label: "Network adapter 2"
          connected: True
          start_connected: True
    loop:
      - { router: '{{ id }}-SA-Router-1', downpg: '{{ id }}-SA-Trunk' }
    delegate_to: localhost
