---
- name : Prepare Horizon Lab #2

  hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "10.10.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "GIT Education"
    cluster_name: "Horizon"

  tasks: 

    - name: 01.Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        state: present
      delegate_to: localhost

    - name: 02.Create Cluster
      community.vmware.vmware_cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
      delegate_to: localhost

    - name: 03.Add ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
        esxi_hostname: '{{ item }}'
        esxi_username: 'root'
        esxi_password: 'VMware1!'
        state: present
      loop:
        - "sa-esxi-01.vclass.local"
        - "sa-esxi-02.vclass.local"
        - "sa-esxi-03.vclass.local"
      delegate_to: localhost


    - name: 04.Enable iSCSI of ESXi
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ item }}"
        state: enabled
      loop:
        - "sa-esxi-01.vclass.local"
        - "sa-esxi-02.vclass.local"
        - "sa-esxi-03.vclass.local"
      delegate_to: localhost

    - name: 05.Add a dynamic target to iSCSI config of ESXi
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ item }}"
        iscsi_config:
          vmhba_name: vmhba65
          send_target:
            address: "10.10.10.2"
        state: present
      loop:
        - "sa-esxi-01.vclass.local"
        - "sa-esxi-02.vclass.local"
        - "sa-esxi-03.vclass.local"

    - name: 06.Recan HBA for cluster
      community.vmware.vmware_host_scanhba:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        cluster_name: '{{ cluster_name }}'
        rescan_hba: true
      delegate_to: localhost

    - name: 07.Wait for complete rescan HBA
      wait_for:
        timeout: 20
      delegate_to: localhost

    - name: 08.Mount iSCSI-01 datastore
      community.vmware.vmware_host_datastore:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datastore_name: 'iSCSI-01'
        datastore_type: 'vmfs'
        vmfs_device_name: 'naa.60003fff44dc75adcba4d2507543dd621'
        vmfs_version: 6
        esxi_hostname: '{{ item }}'
        state: present
      loop:
        - "sa-esxi-01.vclass.local"
        - "sa-esxi-02.vclass.local"
        - "sa-esxi-03.vclass.local"
      delegate_to: localhost

    - name: 09.Create Subscribed Content Library
      community.vmware.vmware_content_library_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        library_name: from-vcsa.edu.git
        library_description: 'Subscribed Library from vcsa.edu.git'
        library_type: subscribed
        datastore_name: iSCSI-01
        subscription_url: 'https://vcsa.edu.git:443/cls/vcsp/lib/7423319a-76be-4c63-821f-13a57f1c042d/lib.json'
        ssl_thumbprint: '47:86:e5:3a:f6:ac:39:1c:9b:d0:39:48:fe:79:18:c2:3f:ba:d5:20'
        update_on_demand: true
        state: present
      delegate_to: localhost


    - name: 10.Add vMotion Portgroup to all hosts in a cluster
      community.vmware.vmware_portgroup:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster_name: "{{ cluster_name }}"
        switch: vSwitch0
        portgroup: vMotion
        vlan_id: 30
      delegate_to: localhost

    - name: 10.Add vMotion vmkernel port
      community.vmware.vmware_vmkernel:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        esxi_hostname: '{{ item.esxi_host }}'
        vswitch_name: vSwitch0
        portgroup_name: vMotion
        network:
          type: 'static'
          ip_address: '{{ item.vmotionip }}'
          subnet_mask: 255.255.255.0
          default_gateway: 10.10.30.1
        state: present
        enable_vmotion: yes
      with_items:
      - { esxi_host: sa-esxi-01.vclass.local, vmotionip: 10.10.30.11 }
      - { esxi_host: sa-esxi-02.vclass.local, vmotionip: 10.10.30.12 }
      - { esxi_host: sa-esxi-03.vclass.local, vmotionip: 10.10.30.13 }
      delegate_to: localhost
      
