---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "vSAN Datacenter"
    cluster_name: "vSAN Cluster"
    esxi_hostname: "172.0.10.13"
    esxi_username: "root"
    esxi_password: "VMware1!"
    student_ID: "S13"

  tasks: 
    - name: Create Lab Standard Switch
      community.vmware.vmware_vswitch:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          validate_certs: no
          switch: '{{ student_ID }}'
#         nics: 
#         mtu: 9000
      delegate_to: localhost


    - name: Waiting 10 seconds for completing switch
      wait_for:
        timeout: 10
      delegate_to: localhost


    - name: Adding Trunk Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Trunk' }}"
          vlan_id: 4095
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Management Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Mgmt' }}"
          vlan_id: 101
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Storage Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-Storage' }}"
          vlan_id: 102
      delegate_to: localhost

    - name: Adding Site A vMotion Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ student_ID }}"
          portgroup: "{{ student_ID + '-vMotion' }}"
          vlan_id: 103
      delegate_to: localhost
