---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    student_id: "S00"
    esxi_hostname: "172.0.10.13"

  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html
  - name: Adding Site A Management Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SA-Mgmt' }}"
      vlan_id: 10
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    delegate_to: localhost

  - name: Adding Site A Storage Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SA-Storage' }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: 11
    delegate_to: localhost

  - name: Adding Site A vMotion Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SA-vMotion' }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: 12
    delegate_to: localhost
      
  - name: Adding Site B Management Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SB-Mgmt' }}"
      vlan_id: 20
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    delegate_to: localhost

  - name: Adding Site B Storage Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SB-Storage' }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: 21
    delegate_to: localhost

  - name: Adding Site B vMotion Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SB-vMotion' }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: 22
    delegate_to: localhost

  - name: Adding Site C Management Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-SC-Mgmt' }}"
      vlan_id: 30
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    delegate_to: localhost

      
  - name: Adding vSAN Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-vSAN' }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: 100
    delegate_to: localhost

  - name: Adding Trunk Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + '-Trunk' }}"
      vlan_id: 4095
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    delegate_to: localhost
