---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: ""
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    student_id: ""
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"
    esxi_hostname: ""
    template_name: "temp-WinSvr2022"
    snapshot_name: "linked"
    datastore_name: "vsanDatastore"    
    
  tasks:
# 5.IaC 폴더에 있는 temp-WinSvr2022 VM에 생성된 linked Snapshot을 이용하여 Student ID값뒤에 "-DC"을 붙여서 VM 생성하기
# 생성된 VM은 각 실습환경 XX-SA-Mgmt 네트워크에 연결되어야 하며, IP : 10.10.10.2/24    GW : 10.10.10.1    DNS : 172.0.10.2 으로 지정되어야 함
# 가상머신 시작시점에서 네트워크 연결이 이뤄져야 함
# AD DS 설치를 위해서 요구되는 시스템 암호 설정은 VMware1! 으로 지정
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-linked_clone  
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-customization
  - name: 06. Linked Clone Windows Server for Domain Controller
    community.vmware.vmware_guest:

      networks:
      - name: "{{ student_id + '-SA-Mgmt' }}"

      
      customization:
        password: VMware1!
      wait_for_customization: yes
      wait_for_customization_timeout: 300
    delegate_to: localhost
