---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    student_id: "S00"
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"

  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_file_operation_module.html
# DC VM 내부에 C:\Material Folder 만들기
  - name: Make folder VM inside    
    community.vmware.vmware_guest_file_operation:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      vm_id: "{{ student_ID + '-DC' }}"
      vm_id_type: vm_name
      vm_username: 'Administrator'
      vm_password: 'VMware1!'

    delegate_to: localhost

# DC VM 내부에 만들어진 /Material 폴더에 PowerShell Script 파일 복사하기
  - name: Copy powershell script to VM
    community.vmware.vmware_guest_file_operation:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      vm_id: "{{ student_id + '-DC' }}"
      vm_id_type: vm_name
      vm_username: 'Administrator'
      vm_password: 'VMware1!'
      copy:
        src: 
        dest: 
        overwrite: true

    delegate_to: localhost

# 복사된 PowerShell 스크립트 파일 실행시키기
  - name: Run dns powershell script
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      vm_id: "{{ student_id + '-DC' }}"
      vm_id_type: vm_name
      vm_username: 'Administrator'
      vm_password: 'VMware1!'
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: 
      vm_shell_cwd: 'c:\Users\Administrator'
      wait_for_process: True
      timeout: 60

    delegate_to: localhost

# VM_Shell 으로는 파일 복사 / 디렉토리 생성만 가능함. Powershell을 이용하여 실행된 Script 파일을 삭제하기
  - name: Delete copied powershell script
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      vm_id: "{{ student_id + '-DC' }}"
      vm_id_type: vm_name
      vm_username: 'Administrator'
      vm_password: 'VMware1!'
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: 
      vm_shell_cwd: 'c:\Users\Administrator'
      wait_for_process: True

    delegate_to: localhost
