
---
- hosts: localhost
  gather_facts: no

#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    student_id: "S00"
    parent_folder: "1.Internal-Training/Students"
    esxi_hostname: "172.0.10.13"
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "DPG-172.0.10.x"
    private_net: "{{ student_id + '-Trunk' }}"
    datastore_name: "vsanDatastore"
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"


  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vcenter_folder_module.html  
  - name: 01. Create a Project folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ student_id }}'
      parent_folder: '{{ parent_folder }}'
      state: present
    register: sub_folder_creation_result
    delegate_to: localhost


# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html  
  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ esxi_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ student_id }}'
    delegate_to: localhost

  - name: waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost

# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html
  - name: 03. Adding Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + item.portgroup }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: '{{ item.vlan }}'
    loop:
    - { portgroup: "-SA-Mgmt", vlan: 10 }
    - { portgroup: "-SA-Storage", vlan: 11 }
    - { portgroup: "-SA-vMotion", vlan: 12 }
    - { portgroup: "-SA-Prod", vlan: 13 }
    - { portgroup: "-SB-Mgmt", vlan: 20 }
    - { portgroup: "-SB-Storage", vlan: 21 }
    - { portgroup: "-SB-vMotion", vlan: 22 }
    - { portgroup: "-SB-Prod", vlan: 23 }
    - { portgroup: "-SC-Mgmt", vlan: 30 }
    - { portgroup: "-vSAN", vlan: 100 }    
    - { portgroup: "-Trunk", vlan: 4095 }
    delegate_to: localhost


  - name: 04. Deploy Router(VyOS) OVA
    community.vmware.vmware_deploy_ovf:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ folder_name }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: '{{ datastore_name }}'
      name: "{{ student_id + '-Router' }}"
      networks: { 'Lab-Outside': "{{ public_net }}", 'Lab-Inside': "{{ private_net }}" }
      ovf: /mnt/c/Material/temp-vyos-1.4.ova    
    delegate_to: localhost

  - name: waiting Router Booting
    wait_for:
      timeout: 60
    delegate_to: localhost    


# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html
# https://docs.vyos.io/en/latest/automation/command-scripting.html
# https://docs.vyos.io/en/latest/quick-start.html#configuration-mode
  - name: 05. Configure Router(VyOS)
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: '{{ folder_name }}'
      vm_id: "{{ student_id + '-Router' }}"
      vm_id_type: vm_name
      vm_username: 'vyos'
      vm_password: 'vyos'
      vm_shell: /bin/vbash
      vm_shell_cwd: "/tmp"
      vm_shell_args: |-
        -c "source /opt/vyatta/etc/functions/script-template
        configure
          set system login user admin full-name Admin_User
          set system login user admin authentication plaintext-password VMware1!
          set service ssh port 22
            
          set system ipv6 disable
          
          set interfaces ethernet eth0 address dhcp
          set interfaces ethernet eth0 description Outside
          set interfaces ethernet eth0 ipv6 address no-default-link-local
          set protocols static route 0.0.0.0/0 next-hop 172.0.10.1

          set interfaces ethernet eth1 vif 10 description 'VLAN 10 - Site A Management'
          set interfaces ethernet eth1 vif 10 address 10.10.10.1/24
          set interfaces ethernet eth1 vif 10 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 11 description 'VLAN 11 - Site A Storage'
          set interfaces ethernet eth1 vif 11 address 10.10.11.1/24
          set interfaces ethernet eth1 vif 11 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 12 description 'VLAN 12 - Site A vMotion'
          set interfaces ethernet eth1 vif 12 address 10.10.12.1/24
          set interfaces ethernet eth1 vif 12 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 13 description 'VLAN 13 - Site A Production'
          set interfaces ethernet eth1 vif 13 address 10.10.13.1/24
          set interfaces ethernet eth1 vif 13 ipv6 address no-default-link-local

          set interfaces ethernet eth1 vif 20 description 'VLAN 20 - Site B Management'
          set interfaces ethernet eth1 vif 20 address 10.10.20.1/24
          set interfaces ethernet eth1 vif 20 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 21 description 'VLAN 21 - Site B Storage'
          set interfaces ethernet eth1 vif 21 address 10.10.21.1/24
          set interfaces ethernet eth1 vif 21 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 22 description 'VLAN 22 - Site B vMotion'
          set interfaces ethernet eth1 vif 22 address 10.10.22.1/24
          set interfaces ethernet eth1 vif 22 ipv6 address no-default-link-local
          set interfaces ethernet eth1 vif 23 description 'VLAN 23 - Site B Production'
          set interfaces ethernet eth1 vif 23 address 10.10.23.1/24
          set interfaces ethernet eth1 vif 23 ipv6 address no-default-link-local

          set interfaces ethernet eth1 vif 30 description 'VLAN 30 - SiteC Management'
          set interfaces ethernet eth1 vif 30 address 10.10.30.1/24
          set interfaces ethernet eth1 vif 30 ipv6 address no-default-link-local

          set interfaces ethernet eth1 vif 100 description 'VLAN 100 - vSAN'
          set interfaces ethernet eth1 vif 100 address 10.10.100.1/24
          set interfaces ethernet eth1 vif 100 ipv6 address no-default-link-local

          set system name-server 172.0.10.2
          set service ntp server kr.pool.ntp.org
                      
          set nat source rule 10 outbound-interface eth0
          set nat source rule 10 source address 10.10.10.0/24
          set nat source rule 10 translation address masquerade

          set nat source rule 13 outbound-interface eth0
          set nat source rule 13 source address 10.10.13.0/24
          set nat source rule 13 translation address masquerade
          
        commit
        save"
      wait_for_process: True
      timeout: 180
    delegate_to: localhost
    register: shell_command_with_wait_timeout        
