---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: ""
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    student_id: ""
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"

  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html
# https://docs.vyos.io/en/latest/automation/command-scripting.html
# https://docs.vyos.io/en/latest/quick-start.html#configuration-mode
  - name: 05. Configure Router(VyOS)
    community.vmware.vmware_vm_shell:

      vm_username: 'vyos'
      vm_password: 'vyos'
      vm_shell: /bin/vbash
      vm_shell_cwd: "/tmp"
      vm_shell_args: |-
        -c "source /opt/vyatta/etc/functions/script-template
        configure
          
        commit
        save"
      wait_for_process: True
      timeout: 180
    delegate_to: localhost
    register: shell_command_with_wait_timeout        
