---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: ""
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    parent_folder: "1.Internal-Training/Students"
    student_id: ""
    esxi_hostname: ""
    public_net:  "DPG-172.0.10.x"
    private_net: "{{  }}"
    datastore_name: "vsanDatastore"

  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_deploy_ovf_module.html  
  - name: 04. Deploy Router(VyOS) OVA
    community.vmware.vmware_deploy_ovf:
    
      networks: { 'Lab-Outside': "{{ public_net }}", 'Lab-Inside': "{{ private_net }}" }
      ovf: /mnt/c/Material/temp-vyos-1.4.ova    
    delegate_to: localhost

  - name: waiting Router Booting
    wait_for:
      timeout: 60
    delegate_to: localhost
