---
- hosts: localhost
  gather_facts: no
#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: ""
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    student_id: ""
    esxi_hostname: ""

  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html
  - name: Adding Site A Management Portgroup
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: 
      portgroup: 
      vlan_id: 10
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
    delegate_to: localhost

