
---
- hosts: localhost
  gather_facts: no

#  vars_files: ./vars.yaml
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "s00@edu.git"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    student_id: "S00"
    parent_folder: "1.Internal-Training/Students"
    esxi_hostname: "172.0.10.13"
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "DPG-172.0.10.x"
    private_net: "{{ student_id + '-Trunk' }}"
    datastore_name: "vsanDatastore"
    folder_name: "{{ datacenter_name + '/vm/' + parent_folder + '/' + student_id }}"


  tasks: 
# https://docs.ansible.com/ansible/latest/collections/community/vmware/vcenter_folder_module.html  
  - name: 01. Create a Project folder
    community.vmware.vcenter_folder:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
      datacenter_name: '{{ datacenter_name }}'
      folder_name: '{{ student_id }}'
      parent_folder: '{{ parent_folder }}'
      state: present
    register: sub_folder_creation_result
    delegate_to: localhost


# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html  
  - name: 02. Create Project Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: '{{ esxi_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      validate_certs: false
      switch: '{{ student_id }}'
    delegate_to: localhost

  - name: waiting vswitch creating
    wait_for:
      timeout: 10
    delegate_to: localhost

# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html
  - name: 03. Adding Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      validate_certs: no
      switch: "{{ student_id }}"
      portgroup: "{{ student_id + item.portgroup }}"
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True
      vlan_id: '{{ item.vlan }}'
    loop:
    - { portgroup: "-SA-Mgmt", vlan: 10 }
    - { portgroup: "-SA-Storage", vlan: 11 }
    - { portgroup: "-SA-vMotion", vlan: 12 }
    - { portgroup: "-SA-Prod", vlan: 13 }
    - { portgroup: "-SB-Mgmt", vlan: 20 }
    - { portgroup: "-SB-Storage", vlan: 21 }
    - { portgroup: "-SB-vMotion", vlan: 22 }
    - { portgroup: "-SB-Prod", vlan: 23 }
    - { portgroup: "-SC-Mgmt", vlan: 30 }
    - { portgroup: "-vSAN", vlan: 100 }    
    - { portgroup: "-Trunk", vlan: 4095 }
    delegate_to: localhost


  - name: 04. Deploy Router(VyOS) OVA
    community.vmware.vmware_deploy_ovf:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ folder_name }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: '{{ datastore_name }}'
      name: "{{ student_id + '-Router' }}"
      networks: { 'Lab-Outside': "{{ public_net }}", 'Lab-Inside': "{{ private_net }}" }
      ovf: /mnt/c/Material/temp-vyos-1.4.ova    
    delegate_to: localhost

  - name: waiting Router Booting
    wait_for:
      timeout: 60
    delegate_to: localhost    
