---
- name: destroy lab
  hosts: localhost
  gather_facts: no
  vars:
    sa_vcsa : "sa-vcsa-01.lab.git"
    sb_vcsa : "sb-vcsa-01.lab.git"
    sc_vcsa : "sc-vcsa-01.lab.git"
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"

    sa_dc: "SA-Datacenter"
    sa_cluster: "SA-vSAN"
    sa_ds: "sa-vSAN"
    sa_fn: "3.SA-Students/"
    
    sb_dc: "SB-Datacenter"
    sb_cluster: "SB-vSAN"
    sb_ds: "sb-vSAN"
    sb_fn: "3.SB-Students/"
    
    sc_dc: "SC-Datacenter"
    sc_cluster: "SC-vSAN"
    sc_ds: "sc-vSAN"
    sc_fn: "3.SC-Students/"

    sa_esxi: "sa-esxi-01.lab.git"
    sb_esxi: "sb-esxi-01.lab.git"
    sc_esxi: "sc-esxi-01.lab.git"
    esxi_username: "root"
    esxi_password: "VMware1!"

    id: "S06"                      ## check existing folder (switch) name

  tasks:
    - name: 01. Site A VM list
      community.vmware.vmware_vm_info:
        hostname: '{{ sa_vcsa }}'
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: '{{ sa_dc }}/vm/{{ sa_fn }}{{ id }}'
      register: sa_vms

    - name: 02. Check sa_vms 
      debug:
        var: sa_vms

    - name: 03. Stop Site A VMs in the folder
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ sa_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sa_dc }}"
        name: "{{ item.guest_name }}"
        state: powered-off
      loop: "{{ sa_vms.virtual_machines }}"

    - name: 04. Delete Site A VMs in the folder
      community.vmware.vmware_guest:
        hostname: "{{ sa_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sa_dc }}"
        folder: '{{ sa_dc }}/vm/{{ sa_fn }}{{ id }}'
        name: "{{ item.guest_name }}"
        state: absent
      loop: "{{ sa_vms.virtual_machines }}"

    - name: 05. Site B VM list
      community.vmware.vmware_vm_info:
        hostname: '{{ sb_vcsa }}'
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: '{{ sb_dc }}/vm/{{ sb_fn }}{{ id }}'
      register: sb_vms

    - name: 06. Check sb_vms 
      debug:
        var: sb_vms

    - name: 07. Stop Site B VMs in the folder
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ sb_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sb_dc }}"
        name: "{{ item.guest_name }}"
        state: powered-off
      loop: "{{ sb_vms.virtual_machines }}"

    - name: 08. Delete Site B VMs in the folder
      community.vmware.vmware_guest:
        hostname: "{{ sb_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sb_dc }}"
        folder: '{{ sb_dc }}/vm/{{ sb_fn }}{{ id }}'
        name: "{{ item.guest_name }}"
        state: absent
      loop: "{{ sb_vms.virtual_machines }}"

    - name: 09. Site C VM list
      community.vmware.vmware_vm_info:
        hostname: '{{ sc_vcsa }}'
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: '{{ sc_dc }}/vm/{{ sc_fn }}{{ id }}'
      register: sc_vms

    - name: 10. Check sc_vms 
      debug:
        var: sc_vms

    - name: 11. Stop Site C VMs in the folder
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ sc_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sc_dc }}"
        name: "{{ item.guest_name }}"
        state: powered-off
      loop: "{{ sc_vms.virtual_machines }}"

    - name: 12. Delete Site C VMs in the folder
      community.vmware.vmware_guest:
        hostname: "{{ sc_vcsa }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ sc_dc }}"
        folder: '{{ sc_dc }}/vm/{{ sc_fn }}{{ id }}'
        name: "{{ item.guest_name }}"
        state: absent
      loop: "{{ sc_vms.virtual_machines }}"


    - name: 13. Remove LAB Standard vSwitch
      community.vmware.vmware_vswitch:
        hostname: '{{ item.host }}'
        username: '{{ esxi_username }}'
        password: '{{ esxi_password }}'
        validate_certs: false
        switch: '{{ item.vswitch }}'
        state: absent
      loop:
        - { host: '{{ sa_esxi }}' , vswitch: '{{ id }}-SA'  }
        - { host: '{{ sb_esxi }}' , vswitch: '{{ id }}-SB'  }
        - { host: '{{ sc_esxi }}' , vswitch: '{{ id }}-SC'  }
      delegate_to: localhost


    - name: 14. Remove LAB VM Folder
      community.vmware.vcenter_folder:
        hostname: '{{ item.VCSA }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        datacenter: '{{ item.DC }}'
        folder_type: vm
        folder_name: '{{ item.ID }}'
        parent_folder: '{{ item.FN }}'
        state: absent
      loop:
      - { VCSA: '{{ sa_vcsa }}' , DC: '{{ sa_dc }}', FN: '{{ sa_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sb_vcsa }}' , DC: '{{ sb_dc }}', FN: '{{ sb_fn }}', ID: '{{ id }}'  }
      - { VCSA: '{{ sc_vcsa }}' , DC: '{{ sc_dc }}', FN: '{{ sc_fn }}', ID: '{{ id }}'  }
      delegate_to: localhost
