---
- name : Single site vSAN Cluster

  hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "vSAN Datacenter"
    cluster_name: "vSAN Cluster"
    datastore_name: "vsanDatastore"    
#    esxi_hostname: "172.0.10.13"
#    student_ID: "S00"
    full_folder_prefix: "vSAN Datacenter/vm/1.Internal-Education/Students/"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no
    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:172.0.10.13)?
      private: no
      
  tasks: 
  - name: Clone multiple esxi vms from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "Temp-ESXi"
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
      - "{{student_ID+'-ESXi-04'}}"
    delegate_to: localhost


  - name: Change vCPU, vRAM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item }}"
      hardware:
        memory_mb: 16384
        num_cpus: 4
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
      - "{{student_ID+'-ESXi-04'}}"
    delegate_to: localhost


  - name: Adding vSAN NVMe Disks
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item }}"
      disk:
        - size_gb: 40
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 0
        - size_gb: 40
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 1
        - size_gb: 200
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 2
        - size_gb: 200
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 3
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
      - "{{student_ID+'-ESXi-04'}}"      
    delegate_to: localhost


# https://stackoverflow.com/questions/59626587/how-to-change-vmware-network-adapter-with-ansible
  - name: Adding ESXi VMs Network Interfaces
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0] }}"
      label: "{{ item[1] }}"
      network_name: "{{ student_ID + '-Trunk' }}"
      state: present
      force: yes
    with_nested:
      - [ "{{student_ID+'-ESXi-01'}}", "{{student_ID+'-ESXi-02'}}", "{{student_ID+'-ESXi-03'}}", "{{student_ID+'-ESXi-04'}}" ]
      - [ "Network adapter 1", "Network adapter 2", "Network adapter 3", "Network adapter 4" ]
    delegate_to: localhost


# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html
  - name: Power on ESXi VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredon"
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
      - "{{student_ID+'-ESXi-04'}}"      
    delegate_to: localhost
  

  - name: Waiting boot-up
    wait_for:
      timeout: 120
    delegate_to: localhost


  - name: Configure ESXi VM
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      vm_id: "{{ item.vm_name }}"
      vm_id_type: vm_name
      vm_username: 'root'
      vm_password: 'VMware1!'
      vm_shell: /bin/sh
      vm_shell_cwd: "/tmp"
      vm_shell_args: |
        echo ---- Don't remove this line. Write your ESXi configuration commands below. ----
        esxcli system settings advanced set -o /Net/FollowHardwareMac -i 1
        sed -i 's#/system/uuid.*##' /etc/vmware/esx.conf
        esxcli network vswitch standard uplink add -u vmnic1 -v vSwitch0
        esxcli network vswitch standard portgroup set -p 'Management Network' -v 10
        esxcli network vswitch standard portgroup set -p 'VM Network' -v 10
        esxcli network ip interface ipv4 set -i vmk0 -t static -I '{{ item.ipaddr }}' -N 255.255.255.0 -g 10.10.10.1
        esxcli network ip route ipv4 add -n 0.0.0.0 -g 10.10.10.1
        esxcli network ip dns server add -s 10.10.10.2
        esxcli system hostname set --host '{{ item.host_name }}'
        esxcli system hostname set --domain vclass.local
        esxcli system ntp set -e yes -s kr.pool.ntp.org
        vim-cmd hostsvc/enable_ssh
        vim-cmd hostsvc/enable_esx_shell
        vim-cmd hostsvc/advopt/update UserVars.SuppressShellWarning long 1
        /sbin/generate-certificates
        /sbin/auto-backup.sh
      wait_for_process: True
    with_items:
    - { vm_name: "{{student_ID+'-ESXi-01'}}", host_name: sa-esxi-01, ipaddr: 10.10.10.11 }
    - { vm_name: "{{student_ID+'-ESXi-02'}}", host_name: sa-esxi-02, ipaddr: 10.10.10.12 }
    - { vm_name: "{{student_ID+'-ESXi-03'}}", host_name: sa-esxi-03, ipaddr: 10.10.10.13 }
    - { vm_name: "{{student_ID+'-ESXi-04'}}", host_name: sa-esxi-04, ipaddr: 10.10.10.14 }
#          esxcli system account set -i=root -p=VMware1! -c=VMware1!


  - name: Reboot ESXi VM
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: 'false'        
      folder: "{{ full_folder_prefix + student_ID }}"
      name: "{{ item }}"
      state: reboot-guest
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
      - "{{student_ID+'-ESXi-04'}}"      
    delegate_to: localhost
