---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "vSAN Datacenter"
    cluster_name: "vSAN Cluster"
#    esxi_hostname: "172.0.10.13"
#    student_ID: "S13"
    datastore_name: "vsanDatastore"
    template_name: "Temp-vSAN-VCSA"
    snapshot_src_name: "Deployed"
    folder_prefix: "1.Internal-Education/Students/"
    full_folder_prefix: "vSAN Datacenter/vm/1.Internal-Education/Students/"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no

    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:172.0.10.13)?
      private: no


  tasks:
  - name: Deploy vCenter Server Appliance VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-VCSA' }}"
      state: "poweredon"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "{{ template_name }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_src_name }}"
      networks:
      - name: "{{ student_ID + '-SA-Mgmt' }}"
        connected: True
        start_connected: True
    delegate_to: localhost
