---
- name : Add SiteB ESXi VMs

  hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    cluster_name: "vSAN"
    datastore_name: "vsanDatastore"    
    full_folder_prefix: "Datacenter/vm/1.Internal-Training/Students/"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no
    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:172.0.10.11, 172.0.10.12, 172.0.10.13)?
      private: no
      
  tasks: 
  - name: Clone multiple esxi vms from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredoff"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "Temp-vSAN-ESXi"
    loop:
      - "{{student_ID+'-SB-ESXi-01'}}"
      - "{{student_ID+'-SB-ESXi-02'}}"
      - "{{student_ID+'-SB-ESXi-03'}}"      
    delegate_to: localhost

# https://stackoverflow.com/questions/59626587/how-to-change-vmware-network-adapter-with-ansible
  - name: Adding ESXi VMs Network Interfaces
    community.vmware.vmware_guest_network:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      networks:
        - label: "Network adapter 1"
          name: "{{ student_ID + '-SB-Mgmt' }}"
          state: present
          connected: yes
          start_connected: yes
        - label: "Network adapter 2"
          name: "{{ student_ID + '-SB-Storage' }}"
          state: present
          connected: yes
          start_connected: yes          
        - label: "Network adapter 3"
          name: "{{ student_ID + '-Trunk' }}"
          state: present
          connected: yes
          start_connected: yes
        - label: "Network adapter 4"
          name: "{{ student_ID + '-Trunk' }}"
          state: present
          connected: yes
          start_connected: yes      
    loop:
      - "{{student_ID+'-SB-ESXi-01'}}"
      - "{{student_ID+'-SB-ESXi-02'}}"
      - "{{student_ID+'-SB-ESXi-03'}}"
    delegate_to: localhost


# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html
  - name: Power on ESXi VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item }}"
      state: "poweredon"
    loop:
      - "{{student_ID+'-SB-ESXi-01'}}"
      - "{{student_ID+'-SB-ESXi-02'}}"
      - "{{student_ID+'-SB-ESXi-03'}}"
    delegate_to: localhost
  

  - name: Waiting boot-up
    wait_for:
      timeout: 120
    delegate_to: localhost


  - name: Configure ESXi VM
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: 'false'
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      vm_id: "{{ item.vm_name }}"
      vm_id_type: vm_name
      vm_username: 'root'
      vm_password: 'VMware1!'
      vm_shell: /bin/sh
      vm_shell_cwd: "/tmp"
      vm_shell_args: |
        echo "Don't remove this line. Write your ESXi configuration commands below."
        esxcli system settings advanced set -o /Net/FollowHardwareMac -i 1
        sed -i 's#/system/uuid.*##' /etc/vmware/esx.conf
        esxcli network ip interface ipv4 set -i vmk0 -t static -I {{ item.ipaddr }} -N 255.255.255.0 -g 10.10.20.1
        esxcli network ip route ipv4 add -n 0.0.0.0 -g 10.10.20.1
        esxcli network ip dns server add -s 10.10.10.2
        esxcli system hostname set --host {{ item.host_name }}
        esxcli system hostname set --domain vclass.local
        esxcli system ntp set -e yes -s 10.10.10.1
        vim-cmd hostsvc/enable_ssh
        vim-cmd hostsvc/enable_esx_shell
        vim-cmd hostsvc/advopt/update UserVars.SuppressShellWarning long 1
        /sbin/generate-certificates
        /sbin/auto-backup.sh
      wait_for_process: True
    with_items:
    - { vm_name: "{{student_ID+'-SB-ESXi-01'}}", host_name: sb-esxi-01, ipaddr: 10.10.20.11 }
    - { vm_name: "{{student_ID+'-SB-ESXi-02'}}", host_name: sb-esxi-02, ipaddr: 10.10.20.12 }
    - { vm_name: "{{student_ID+'-SB-ESXi-03'}}", host_name: sb-esxi-03, ipaddr: 10.10.20.13 }


  - name: Reboot ESXi VM
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: 'false'        
      folder: "{{ full_folder_prefix + student_ID }}"
      name: "{{ item }}"
      state: reboot-guest
    loop:
      - "{{student_ID+'-SB-ESXi-01'}}"
      - "{{student_ID+'-SB-ESXi-02'}}"
      - "{{student_ID+'-SB-ESXi-03'}}"
    delegate_to: localhost
