---
- name : Single site vSAN Cluster

  hosts: localhost

  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "172.0.10.10"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware1!"
    datacenter_name: "Datacenter"
    cluster_name: "vSAN"
    datastore_name: "vsanDatastore"    
    full_folder_prefix: "Datacenter/vm/1.Internal-Training/Students/"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no
      
  tasks: 
  - name: Adding vSAN NVMe Disks
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ item }}"
      disk:
        - size_gb: 40
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 0
        - size_gb: 40
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 1
        - size_gb: 200
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 2
        - size_gb: 200
          state: present
          controller_type: nvme
          controller_number: 0
          unit_number: 3
    loop:
      - "{{student_ID+'-ESXi-01'}}"
      - "{{student_ID+'-ESXi-02'}}"
      - "{{student_ID+'-ESXi-03'}}"
    delegate_to: localhost
