---
- hosts: loadbalencers
  vars:
    firewall_ports:
      - "80/tcp"
      - "443/tcp"
      - "6443/tcp"
    packages:
      - curl
      - vim
      - net-tools
      - haproxy
      - keepalived

  tasks:
    - name: Install necessary packages
      yum:
        name: "{{ packages }}"
        state: present

    - name: Set SELinux boolean for HAProxy
      seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes

    - name: Configure firewall to allow specific ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop: "{{ firewall_ports }}"

    - name: Configure HAProxy
      copy:
        mode: '0644'
        dest: /etc/haproxy/haproxy.cfg
        content: |
          global
              log /dev/log  local0 warning
              chroot      /var/lib/haproxy
              pidfile     /var/run/haproxy.pid
              maxconn     4000
              user        haproxy
              group       haproxy
              daemon
              
             stats socket /var/lib/haproxy/stats

          defaults
            log global
            option  httplog
            option  dontlognull
                  timeout connect 5000
                  timeout client 50000
                  timeout server 50000

          frontend k8s-controller
            bind *:6443
            mode tcp
            option tcplog
            default_backend k8s-controller

          backend k8s-controller
              mode tcp
              option tcplog
              option tcp-check
              balance roundrobin
              default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
              server k8s-controller1 172.16.0.11:6443 check
              server k8s-controller2 172.16.0.12:6443 check
              server k8s-controller3 172.16.0.13:6443 check
      notify: Restart HAProxy

    - name: Configure keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'
      notify: Restart Keepalived

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
        enabled: yes

    - name: Restart Keepalived  
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
