---
- name: Snapshot_LAB_VMs
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3

    student_id: "A00"                                ## 해당값을 변경해 주세요. 폴더/스위치/포트그룹/VM명을 유니크하게 사용하기 위해서 사용됩니다.

    vcenter_hostname: "sa-vcsa-01.lab.git"           ## student_id 값에 따라서 접속해야할 vCenter가 다른경우에는 변경해주시길 바랍니다.
    vcenter_username: "administrator@vsphere.lab"
    vcenter_password: "VMware1!"
    datacenter_name: "SA-Datacenter"                 ## student_id 값에 따라서 접속해야할 vCenter/Datacenter가 다른경우에는 변경해주시길 바랍니다.
    parent_folder: "3.SA-Students/"                  ## student_id 값에 따라서 접속해야할 vCenter/VM Folder가 다른경우에는 변경해주시길 바랍니다.

    Linux_VMs:
    - { hostname: haproxy1, ip: 172.16.0.8 }
    - { hostname: haproxy2, ip: 172.16.0.9 }
    - { hostname: k8s-contoller1, ip: 172.16.0.11 }
    - { hostname: k8s-contoller2, ip: 172.16.0.12 }
    - { hostname: k8s-contoller3, ip: 172.16.0.13 }
    snapshot_name: before_task
    
  vars_prompt:
  - name: snapshot_task
    prompt: "Which snapshot task want? (create/revert/remove)"
    private: no
    default: "create"

  handlers:
  - name: Start VM after revert
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}" 
      password: "{{ vcenter_password }}"
      name: "{{ student_id }}-{{ item.hostname }}"
      state: powered-on
    loop: "{{ Linux_VMs }}"  

  tasks:
  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{student_id}}"
      name: "{{student_id}}-{{ item.hostname }}"
      state: present
      snapshot_name: "{{ snapshot_name }}"
    loop: "{{ Linux_VMs }}"    
    delegate_to: localhost
    when: snapshot_task == "create"
  
  - name: Revert to a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{student_id}}"
      name: "{{student_id}}-{{ item.hostname }}"
      state: revert
      snapshot_name: "{{ snapshot_name }}"
    loop: "{{ Linux_VMs }}"    
    delegate_to: localhost
    when: snapshot_task == "revert"
    notify: Start VM after revert
  
  - name: Remove a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{student_id}}"
      name: "{{student_id}}-{{ item.hostname }}"
      state: absent
      snapshot_name: "{{ snapshot_name }}"
    loop: "{{ Linux_VMs }}"    
    delegate_to: localhost
    when: snapshot_task == "remove"
  
