---
- name: Deploy Template VM to each Host
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.rapa"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware123!"
    datacenter_name: "Mokdong" 
    esxi_username: "root"
    esxi_password: "Pa$$w0rd"
    parent_folder: "1Day-Class/Templates" 

    Host_Datastore: 
#    - { host: 192.168.2.241, datastore: 192.168.2.241-Local1 }
    - { host: 192.168.2.242, datastore: 192.168.2.242-Local1 }
    - { host: 192.168.2.243, datastore: 192.168.2.243-Local1 }
    - { host: 192.168.2.244, datastore: 192.168.2.244-Local2 }
    - { host: 192.168.2.245, datastore: 192.168.2.245-Local1 }
    - { host: 192.168.2.246, datastore: 192.168.2.246-Local1 }


  tasks:

  - name: 01. Deploy Lab DC template to each host
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.host }}-DC"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.datastore }}"
      template: "192.168.2.241-DC"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 02. Create a snapshot for linked Clone
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      name: "{{item.host}}-DC"
      state: present
      snapshot_name: "Linked"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 03. Deploy Lab VCSA template to each host
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.host }}-VCSA"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.datastore }}"
      template: "192.168.2.241-VCSA"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 04. Create a snapshot for linked Clone
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      name: "{{item.host}}-VCSA"
      state: present
      snapshot_name: "Linked"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost


  - name: 05. Deploy Lab ESXi-01 template to each host
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.host }}-ESXi-01"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.datastore }}"
      template: "192.168.2.241-ESXi-01"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 06. Create a snapshot for linked Clone
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      name: "{{item.host}}-ESXi-01"
      state: present
      snapshot_name: "Linked"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost


  - name: 07. Deploy Lab ESXi-02 template to each host
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.host }}-ESXi-02"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.datastore }}"
      template: "192.168.2.241-ESXi-02"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 08. Create a snapshot for linked Clone
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      name: "{{item.host}}-ESXi-02"
      state: present
      snapshot_name: "Linked"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 09. Deploy Lab ESXi-03 template to each host
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.host }}-ESXi-03"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.datastore }}"
      template: "192.168.2.241-ESXi-03"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost

  - name: 10. Create a snapshot for linked Clone
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}"
      name: "{{item.host}}-ESXi-03"
      state: present
      snapshot_name: "Linked"
    loop: "{{ Host_Datastore }}"
    delegate_to: localhost
