---
- name: Configure NIC Teaming, VLAN NICs, IPs, IPv6 binding, Firewall on Windows and FQDN
  hosts: dc
  gather_facts: no
  vars:
    DNS_Records:
      - { name: loginsight, ip: 10.10.10.9 }
      - { name: sa-vcsa-01, ip: 10.10.10.10 }
      - { name: sa-esxi-01, ip: 10.10.10.22 }
      - { name: sa-esxi-02, ip: 10.10.10.31 }
      - { name: sa-esxi-03, ip: 10.10.10.32 }

    team_name: LabVlan
    team_members:
      - Ethernet2
    teaming_mode: SwitchIndependent      # PowerShell: -TeamingMode SwitchIndependent
    load_balancing_algorithm: Transport  # PowerShell: -LoadBalancingAlgorithm Transport

    vlans:
      - { id: 11, name: "VLAN11", ip: "10.10.11.1", prefix: 24 }
      - { id: 12, name: "VLAN12", ip: "10.10.12.1", prefix: 24 }
      - { id: 13, name: "VLAN13", ip: "10.10.13.1", prefix: 24 }

    disable_ipv6_nics:
      - VLAN11
      - VLAN12
      - VLAN13
      - "{{ team_members | list }}"

    # 방화벽 규칙 명칭
    icmp_rule_name: "Allow inbound ICMPv4"

  tasks:
    - name: Add Forward DNS records
      community.windows.win_dns_record:
        state: present
        name: "{{ item.name }}"
        type: "A"
        value: "{{ item.ip }}"
        zone: "vclass.local"
      loop: "{{ DNS_Records }}"

    - name: Add Reverse DNS records
      community.windows.win_dns_record:
        state: present
        name: "{{ item.ip.split('.')[-1] }}"
        type: "PTR"
        value: "{{ item.name}}.vclass.local"
        zone: "10.10.10.in-addr.arpa"
      loop: "{{ DNS_Records }}"

    - name: Ensure NIC Team exists with desired properties
      community.windows.win_net_lbfo_team:
        name: "{{ team_name }}"
        members: "{{ team_members }}"
        teaming_mode: "{{ teaming_mode }}"
        load_balancing_algorithm: "{{ load_balancing_algorithm }}"
        state: present
      register: team_result

    - name: Ensure VLAN Team NICs exist
      community.windows.win_net_lbfo_team_nic:
        team: "{{ team_name }}"
        name: "{{ item.name }}"
        vlan_id: "{{ item.id }}"
        state: present
      loop: "{{ vlans }}"
      register: vlan_nic_result

    - name: Assign IPv4 addresses to VLAN NICs
      community.windows.win_net_ipaddress:
        interface_alias: "{{ item.name }}"
        ip_address: "{{ item.ip }}"
        prefix_length: "{{ item.prefix }}"
        state: present
      loop: "{{ vlans }}"

    # 주의: 와일드카드(*) 대신 명시적 NIC 목록을 사용하여 안전 적용
    - name: Disable IPv6 binding on selected adapters
      community.windows.win_net_adapter_binding:
        name: "{{ item }}"
        component_id: ms_tcpip6
        state: disabled
      loop: "{{ disable_ipv6_nics | flatten }}"
      ignore_errors: no

    - name: Ensure firewall rule for inbound ICMPv4 echo is present and enabled
      community.windows.win_firewall_rule:
        name: "{{ icmp_rule_name }}"
        display_name: "{{ icmp_rule_name }}"
        enabled: yes
        state: present
        direction: in
        action: allow
        profiles:
          - domain
          - private
          - public
        protocol: icmpv4
        icmp_types:
          - 8

    # 필요 시 재부팅(드라이버/바인딩 변화 후)
    - name: Reboot if required
      ansible.windows.win_reboot:
      when: ansible_reboot_pending | default(false) or team_result.reboot_required | default(false)
